import Header from '@/components/header/header'
import Providers from '@/util/Providers'
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

// pages/_app.js 
import 'normalize.css/normalize.css'

const inter = Inter({ subsets: ["latin"] })

import { NextProviders } from '@/util/NextProviders'

import { ClerkProvider } from '@clerk/nextjs'

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider>
          <Providers>
            <NextProviders>
              <Header />
              {children}
            </NextProviders>
          </Providers>
        </ClerkProvider>
      </body>
    </html>
  )
}
