import Header from '@/components/header/header'
import Providers from '@/util/Providers'
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

const inter = Inter({ subsets: ["latin"] })

import { NextUIProvider } from "@nextui-org/react"
import { NextProviders } from '@/util/NextProviders'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NextProviders>
            <Header />
            {children}
          </NextProviders>
        </Providers>
      </body>
    </html>
  )
}
